name: Build and Release Midnight Commander (mc-4.8.33)

on:
  push:
    paths:
      - ".github/workflows/mc-static.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        run: |
          echo "MC_VERSION=4.8.33" >> $GITHUB_ENV
          echo "FINAL_VERSION=mc-$MC_VERSION-static" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar \
            libncursesw5-dev libglib2.0-dev pkg-config

      - name: Download and extract Midnight Commander source
        run: |
          wget --no-check-certificate https://github.com/MidnightCommander/mc/archive/refs/tags/${MC_VERSION}.tar.gz -O mc.tar.gz
          tar -xf mc.tar.gz
          mv mc-${MC_VERSION} mc-source

      - name: Configure and build static binary
        run: |
          cd mc-source
          LDFLAGS="-static" ./configure --prefix=/usr/local
          make -j$(nproc)

      - name: Retrieve binary and prepare release asset
        run: |
          cp mc-source/src/mc $GITHUB_WORKSPACE/mc-static
          zip mc-${FINAL_VERSION}.zip mc-static

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.FINAL_VERSION }}
          name: "Midnight Commander ${{ env.FINAL_VERSION }}"
          body: |
            Statically linked x86-64 executable
            **Release Version:** ${{ env.FINAL_VERSION }}
            **Build Date:** ${{ env.BUILD_DATE }}
            **Commit:** ${{ github.sha }}
          artifacts: mc-${{ env.FINAL_VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
