name: Build and Release Static Midnight Commander (mc-4.8.33)

on:
  push:
    paths:
      - ".github/workflows/mc-static.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MC_VERSION: "4.8.33"
      FINAL_VERSION: "mc-4.8.33-static"
      BUILD_DATE: ${{ github.run_date }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar \
            libncursesw5-dev libglib2.0-dev pkg-config

      - name: Download and extract Midnight Commander
        run: |
          wget --no-check-certificate https://ftp.midnight-commander.org/${MC_VERSION}.tar.xz
          tar -xf ${MC_VERSION}.tar.xz

      - name: Configure and build static binary with VFS enabled
        run: |
          cd ${MC_VERSION}
          LDFLAGS="-static" ./configure --prefix=/usr/local
          make -j$(nproc)

      - name: Retrieve binary
        run: |
          cp ${MC_VERSION}/src/mc $GITHUB_WORKSPACE/mc-static
          zip mc-${FINAL_VERSION}.zip mc-static

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.FINAL_VERSION }}
          name: "Midnight Commander ${{ env.FINAL_VERSION }}"
          body: |
            Statically linked x86-64 executable
            **Release Version:** ${{ env.FINAL_VERSION }}
            **Build Date:** ${{ env.BUILD_DATE }}
            **Commit:** ${{ github.sha }}
          artifacts: |
            mc-${{ env.FINAL_VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mc-static-artifact
          path: mc-${{ env.FINAL_VERSION }}.zip
