name: Build and Release Static MinIO mc (RELEASE.2025-05-21T01-59-54Z)

on:
  push:
    paths:
      - ".github/workflows/mc-static.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MC_VERSION: "RELEASE.2025-05-21T01-59-54Z"
      FINAL_VERSION: "mc-${{ env.MC_VERSION }}-static"
      BUILD_DATE: ${{ github.run_date }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar \
            libncursesw5-dev libglib2.0-dev pkg-config

      - name: Download and extract MinIO mc source
        run: |
          wget --no-check-certificate https://github.com/minio/mc/archive/refs/tags/${MC_VERSION}.tar.gz -O mc.tar.gz
          tar -xf mc.tar.gz
          mv mc-${MC_VERSION} mc-source

      - name: Configure and build static binary
        run: |
          cd mc-source
          LDFLAGS="-static" ./configure --prefix=/usr/local
          make -j$(nproc)

      - name: Retrieve binary and prepare release asset
        run: |
          cp mc-source/mc $GITHUB_WORKSPACE/mc-static
          zip mc-${FINAL_VERSION}.zip mc-static

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.FINAL_VERSION }}
          name: "MinIO mc ${{ env.FINAL_VERSION }}"
          body: |
            Statically linked x86-64 executable
            **Release Version:** ${{ env.FINAL_VERSION }}
            **Build Date:** ${{ env.BUILD_DATE }}
            **Commit:** ${{ github.sha }}
          artifacts: mc-${{ env.FINAL_VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
