name: vim-static

on:
  push:
    paths:
      - ".github/workflows/vim-static.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Clone the official Vim repository.
      - name: Clone Vim Source
        run: |
          git clone https://github.com/vim/vim.git

      # Step 3: Install required build dependencies.
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev autoconf zip

      # Step 4: Set a build version based on the GitHub run number.
      - name: Set Build Version
        run: |
          echo "BUILD_VERSION=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "Build version set to ${BUILD_VERSION}"
        shell: bash

      # Step 5: Build Vim with static linking.
      - name: Build Vim (Static x64)
        run: |
          cd vim
          # Clean any previous build artifacts if they exist.
          [ -f Makefile ] && make clean || echo "No previous build detected"
          # If the 'configure' script is missing, generate it.
          [ ! -f configure ] && ./autogen.sh
          # Configure Vim with huge features and force static linking.
          ./configure --with-features=huge --enable-static --disable-dynamic --prefix=$GITHUB_WORKSPACE/build
          # Build Vim enforcing static linking.
          make LDFLAGS=-static -j$(nproc)
          # Install Vim into the build directory.
          make install
        shell: bash

      # Step 6: Prepare the release files.
      # Copy the built Vim executable and create a release info file.
      - name: Prepare Release Files
        run: |
          mkdir release_temp
          cp build/bin/vim release_temp/vim
          echo "Release Version: ${BUILD_VERSION}" > release_temp/release_info.txt
          echo "Build Date: $(date)" >> release_temp/release_info.txt
          echo "Commit: ${{ github.sha }}" >> release_temp/release_info.txt
        shell: bash

      # Step 7: Create a ZIP archive that directly contains the files.
      - name: Create Release Zip
        run: |
          # The -j option discards the path information,
          # so the zip file will contain only 'vim' and 'release_info.txt'
          zip -j vim-${BUILD_VERSION}.zip release_temp/vim release_temp/release_info.txt
        shell: bash

      # Step 8: Upload the ZIP artifact.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vim-static-${{ env.BUILD_VERSION }}
          path: vim-${{ env.BUILD_VERSION }}.zip

      # Step 9: Create a GitHub Release and attach the ZIP file.
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.BUILD_VERSION }}
          name: "Vim ${BUILD_VERSION}"
          body: |
            **Release Version:** ${BUILD_VERSION}
            **Build Date:** $(date)
            **Commit:** ${{ github.sha }}
          files: vim-${{ env.BUILD_VERSION }}.zip
