# .github/workflows/windows-server-2025-iso.yml
name: Windows Server 2025 Custom ISO Build with Intel Wi-Fi Drivers

on:
  push:
    paths:
      - '.github/workflows/windows-server-2025-iso.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install 7-Zip
        run: |
          choco install 7zip.install -y
          7z  # display version info to verify installation

      - name: Download Windows Server 2025 ISO (Verbose)
        run: |
          Invoke-WebRequest -Uri "https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1742.240906-0331.ge_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso" -OutFile "Windows_Server_2025.iso" -Verbose
          Get-Item "Windows_Server_2025.iso"
          dir

      - name: Verify ISO Exists Before Mounting
        run: |
          if (!(Test-Path "Windows_Server_2025.iso")) {
            Write-Host "ISO file missing! Exiting..."
            exit 1
          }

      - name: Mount ISO and Extract Files
        run: |
          $isoPath = (Resolve-Path "Windows_Server_2025.iso").Path
          Mount-DiskImage -ImagePath $isoPath
          $isoDrive = (Get-Volume | Where-Object { $_.DriveType -eq 'CD-ROM' }).DriveLetter
          Write-Host "Detected ISO Drive: $isoDrive"
          
          if (!$isoDrive) {
            Write-Host "ISO mount failed! Exiting..."
            exit 1
          }
          
          if (Test-Path ".\ISO_Contents") {
            Remove-Item ".\ISO_Contents" -Recurse -Force
          }
          New-Item -ItemType Directory -Path ".\ISO_Contents"
          Copy-Item "$($isoDrive):\*" -Destination ".\ISO_Contents" -Recurse -Force

      - name: Download Intel Wireless Wi-Fi Drivers (Verbose)
        run: |
          Invoke-WebRequest -Uri "https://downloadmirror.intel.com/853377/WiFi-23.130.1-Driver64-Win10-Win11.exe" -OutFile "WiFi_Driver.exe" -Verbose
          Get-Item "WiFi_Driver.exe"
          dir

      - name: Extract and Integrate Drivers using 7-Zip
        run: |
          if (!(Test-Path "WiFi_Driver.exe")) {
            Write-Host "WiFi driver executable missing! Exiting..."
            exit 1
          }
          
          Write-Host "Extracting WiFi Driver using 7-Zip..."
          7z x WiFi_Driver.exe -oDrivers -y
          
          Write-Host "Listing extracted files in .\Drivers:"
          dir .\Drivers
          
          if (!(Test-Path ".\Drivers") -or ((Get-ChildItem .\Drivers -Recurse | Measure-Object).Count -eq 0)) {
            Write-Host "Driver extraction failed! Exiting..."
            exit 1
          }
          
          Write-Host "Injecting extracted drivers into the ISO..."
          dism /Image:".\ISO_Contents" /Add-Driver /Driver:".\Drivers" /Recurse

      - name: Enable Wireless LAN Service
        run: |
          Install-WindowsFeature -Name Wireless-Networking

      - name: Repack Customized ISO
        run: |
          oscdimg -n -m -b".\ISO_Contents\boot\etfsboot.com" ".\ISO_Contents" "Windows_Server_2025_Custom.iso"

      - name: Release Updated ISO
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Windows_Server_2025_Custom.iso"
          tag: "v2025.4"
          name: "Windows Server 2025 ISO with Intel Wi-Fi Drivers (7‑Zip extraction)"
          body: "This release includes Intel Wireless Wi-Fi drivers extracted using 7‑Zip and integrated into the installation media."
