# .github/workflows/windows-server-2025-iso.yml
name: Windows Server 2025 Custom ISO Build with Intel Wi-Fi Drivers

on:
  push:
    paths:
      - '.github/workflows/windows-server-2025-iso.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install 7‑Zip (for diagnostic purposes)
        run: |
          choco install 7zip.install -y
          7z

      - name: Download Windows Server 2025 ISO (Verbose)
        run: |
          Invoke-WebRequest -Uri "https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/26100.1742.240906-0331.ge_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso" -OutFile "Windows_Server_2025.iso" -Verbose
          Get-Item "Windows_Server_2025.iso"
          dir

      - name: Verify ISO Exists Before Mounting
        run: |
          if (!(Test-Path "Windows_Server_2025.iso")) {
            Write-Host "ISO file missing! Exiting..."
            exit 1
          }

      - name: Mount ISO and Extract Files
        run: |
          $isoPath = (Resolve-Path "Windows_Server_2025.iso").Path
          Mount-DiskImage -ImagePath $isoPath
          $isoDrive = (Get-Volume | Where-Object { $_.DriveType -eq 'CD-ROM' }).DriveLetter
          Write-Host "Detected ISO Drive: $isoDrive"
          if (!$isoDrive) {
            Write-Host "ISO mount failed! Exiting..."
            exit 1
          }
          if (Test-Path ".\ISO_Contents") {
            Remove-Item ".\ISO_Contents" -Recurse -Force
          }
          New-Item -ItemType Directory -Path ".\ISO_Contents"
          Copy-Item "$($isoDrive):\*" -Destination ".\ISO_Contents" -Recurse -Force

      - name: Download Intel Wireless Wi-Fi Drivers (Verbose)
        run: |
          Invoke-WebRequest -Uri "https://downloadmirror.intel.com/853377/WiFi-23.130.1-Driver64-Win10-Win11.exe" -OutFile "WiFi_Driver.exe" -Verbose
          Get-Item "WiFi_Driver.exe"
          dir

      - name: Extract and Integrate Drivers
        run: |
          if (!(Test-Path "WiFi_Driver.exe")) {
            Write-Host "WiFi driver executable missing! Exiting..."
            exit 1
          }
          Write-Host "Starting driver extraction using InstallShield-style switches..."
          rem Attempt extraction using InstallShield silent extraction flags:
          cmd /c "WiFi_Driver.exe /s /x /v\"/qn TARGETDIR=\\\".\Drivers\\\"\""
          Write-Host "Driver extraction command finished. Waiting 20 seconds for process to complete..."
          Start-Sleep -Seconds 20
          
          Write-Host "Listing extracted files in .\Drivers:"
          dir .\Drivers
          
          if (!(Test-Path ".\Drivers") -or ((Get-ChildItem .\Drivers -Recurse | Measure-Object).Count -eq 0)) {
            Write-Host "Driver extraction failed! Exiting..."
            exit 1
          }

          rem -----------------------------------------------
          rem Now inject the extracted drivers into the offline Windows image.
          rem Typically, the ISO contains install.wim in the sources folder.
          rem -----------------------------------------------
          if (!(Test-Path ".\ISO_Contents\sources\install.wim")) {
              Write-Host "install.wim not found! Verify the ISO structure."
              exit 1
          }
          if (Test-Path ".\mount") {
              Remove-Item ".\mount" -Recurse -Force
          }
          New-Item -ItemType Directory -Path ".\mount"
          
          Write-Host "Mounting install.wim..."
          dism /Mount-Image /ImageFile:".\ISO_Contents\sources\install.wim" /index:1 /MountDir:".\mount"
          
          Write-Host "Injecting extracted drivers into the offline image..."
          dism /Image:".\mount" /Add-Driver /Driver:".\Drivers" /Recurse
          
          Write-Host "Unmounting and committing changes to install.wim..."
          dism /Unmount-Image /MountDir:".\mount" /Commit

      - name: Enable Wireless LAN Service
        run: |
          Install-WindowsFeature -Name Wireless-Networking

      - name: Repack Customized ISO
        run: |
          oscdimg -n -m -b".\ISO_Contents\boot\etfsboot.com" ".\ISO_Contents" "Windows_Server_2025_Custom.iso"

      - name: Release Updated ISO
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Windows_Server_2025_Custom.iso"
          tag: "v2025.5"
          name: "Windows Server 2025 ISO with Intel Wi-Fi Drivers"
          body: "This release integrates Intel Wireless Wi-Fi drivers into the offline image using InstallShield extraction."
